### ISSUE TITLE
Aptosid repository

### ISSUE THREAD

**Issue by GoliathLabs** [repology/repology-updater#1060]
I'd like to see Aptosid being added to the repology-updater, but no hurry :)
http://aptosid.com/debian/

**Comment by AMDmi3** [comment]
There are 4 packages intersecting with other repositories. Why do we need this?

**Comment by AMDmi3** [comment]
I see no reason to add this. Config entry in case someone needs this:

```yaml
- name: aptosid
  type: repository
  desc: aptosid
  statsgroup: Debian+derivs
  family: debuntu
  ruleset: [debuntu,aptosid]
  minpackages: 20
  sources:
    - name: main
      fetcher: FileFetcher
      parser: DebianSourcesParser
      url: http://aptosid.com/debian/dists/sid/main/source/Sources.xz
      compression: xz
  repolinks:
    - desc: aptosid home
      url: http://aptosid.com/
  tags: [ all, production ]
```
