### ISSUE TITLE
EndeavourOS

### ISSUE THREAD

**Issue by GoliathLabs** [repology/repology-updater#1061]
EndeavourOS is the de-facto successor of Antergos
https://github.com/endeavouros-team/PKGBUILDS

**Comment by AMDmi3** [comment]
Need something similar to antergos.db.tar.gz, as Repology does not parse PKGBUILDs. However does not make much sense as there are less than a dozen non-unique packages.

**Comment by GoliathLabs** [comment]
https://github.com/endeavouros-team/repo/blob/master/endeavouros/x86_64/endeavouros.db.tar.xz
Wrong repository. My fault :/

**Comment by AMDmi3** [comment]
There are 4 packages intersecting with other repositories. Why do we need this?

**Comment by AMDmi3** [comment]
I see no reason to add this. Config entry in case somebody needs this:

```yaml
- name: endeavoros
  type: repository
  desc: EndeavorOS
  statsgroup: Arch+derivs
  family: arch
  minpackages: 1
  sources:
    - name: x86_64
      fetcher: TarFetcher
      parser: ArchDBParser
      url: 'https://github.com/endeavouros-team/repo/raw/master/endeavouros/x86_64/endeavouros.db.tar.xz'
      subrepo: '{source}'
  tags: [ all, production ]
```
