### ISSUE TITLE
Add GRML

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#1067]
Debian based, grml.org

**Comment by AMDmi3** [comment]
Useless, only 14 non-unique packages. Configs for history:

```yaml
- name: grml-stable
  type: repository
  desc: GRML stable
  statsgroup: Debian+derivs
  family: debuntu
  minpackages: 0
  sources:
    - name: main
      fetcher: FileFetcher
      parser: DebianSourcesParser
      url: http://deb.grml.org/dists/grml-stable/main/source/Sources.gz
      compression: gz
  repolinks:
    - desc: grml.org
      url: https://grml.org/
  tags: [ all, grml ]

- name: grml-testing
  type: repository
  desc: GRML testing
  statsgroup: Debian+derivs
  family: debuntu
  minpackages: 0
  sources:
    - name: main
      fetcher: FileFetcher
      parser: DebianSourcesParser
      url: http://deb.grml.org/dists/grml-testing/main/source/Sources.gz
      compression: gz
  repolinks:
    - desc: grml.org
      url: https://grml.org/
  tags: [ all, grml ]

- name: grml-2020.06
  type: repository
  desc: GRML 2020.06
  statsgroup: Debian+derivs
  family: debuntu
  minpackages: 0
  sources:
    - name: main
      fetcher: FileFetcher
      parser: DebianSourcesParser
      url: http://deb.grml.org/dists/grml-2020.06/main/source/Sources.gz
      compression: gz
  repolinks:
    - desc: grml.org
      url: https://grml.org/
  tags: [ all, grml ]
```
